const express = require("express");
const app = express();
const cookieParser = require("cookie-parser");
const bodyParser = require("body-parser");
const fileUpload = require("express-fileupload");
const errorMiddleware = require("./middlewares/error");
app.use(cookieParser());
app.use(bodyParser.urlencoded({ extended: true }));
app.use(errorMiddleware);
module.exports = app;
